/** M1D safe sender layouts; network canaries point ONLY to the local test app. */
export function fidelityFixtures() {
  const rows = Array.from({length: 80}, (_, i) => `<tr><td style="padding:16px;border:1px solid #ccddee">Enterprise item ${i}</td><td style="padding:16px;border:1px solid #ccddee">Synthetic detail</td></tr>`).join("");
  return [
    {name:"ENTERPRISE_TABLE",end:"ACTUAL_END_ENTERPRISE",html:`<table width="600" cellpadding="24" cellspacing="0" bgcolor="#eef2f6" style="width:600px;max-width:100%;margin:0 auto;border-collapse:collapse"><tr><td style="padding:24px;background-color:#16324f;color:#fff"><h1 style="font-family:Georgia, serif;font-size:32px;margin:0">ECH TEST ENTERPRISE</h1></td></tr><tr><td style="padding:24px"><table width="100%" style="border-collapse:collapse">${rows}</table><p>ACTUAL_END_ENTERPRISE</p></td></tr></table>`},
    {name:"APPLE_STYLE_NO_IMAGES",end:"ACTUAL_END_APPLE",html:`<div style="max-width:600px;margin:0 auto;padding:24px;background-color:#f5f5f7;font-family:Arial, Helvetica, sans-serif;text-align:center"><h1 style="font-size:48px;line-height:1.1;margin:24px 0;color:#1d1d1f">A clearer day.</h1><p style="font-size:24px;line-height:1.5;margin:24px 0;color:#555">Synthetic newsletter. Safe typography and generous spacing.</p><a href="https://example.invalid/information" style="padding:12px 24px;border:1px solid #0071e3;border-radius:20px;color:#0071e3;text-decoration:none">Learn more</a>${Array.from({length:30},(_,i)=>`<h2 style="font-size:32px;margin:32px 0 16px">Designed section ${i}</h2><p style="margin:16px 0;line-height:1.6">Synthetic readable description with no images.</p>`).join("")}<p>ACTUAL_END_APPLE</p></div>`},
    {name:"MALICIOUS_CSS",end:"ACTUAL_END_CSS_SAFE",html:`<style>@import url(http://127.0.0.1:3299/m1d-network-canary/import);body{position:fixed;inset:0;background:red}</style><div class="cover" style="position:fixed;inset:0;z-index:999999;background-image:url(http://127.0.0.1:3299/m1d-network-canary/css);width:expression(alert(1));transform:scale(100);padding:16px;border:1px solid #123456">SAFE_CSS_CONTENT</div><img src="http://127.0.0.1:3299/m1d-network-canary/image" onerror="document.body.dataset.m1dExecuted='event'"><script>document.body.dataset.m1dExecuted='script'</script><form action="http://127.0.0.1:3299/m1d-network-canary/form"><input><button>Submit</button></form><iframe src="http://127.0.0.1:3299/m1d-network-canary/frame"></iframe><object data="http://127.0.0.1:3299/m1d-network-canary/object"></object><embed src="http://127.0.0.1:3299/m1d-network-canary/embed"><a href="javascript:document.body.dataset.m1dExecuted='link'">BAD_LINK</a><p onclick="document.body.dataset.m1dExecuted='click'">SAFE_CLICK_TARGET</p><p>ACTUAL_END_CSS_SAFE</p>`},
  ];
}
