/** Authenticated disposable-runtime acceptance. Never sends; no Production route. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
const runtime=process.env.M1H_RUNTIME, evidence=process.env.M1H_EVIDENCE;
if(!runtime||!path.basename(runtime).startsWith('crm-mail-mobile-m1h-')||!evidence)throw Error('Disposable M1H runtime/evidence required');
const config=JSON.parse(await readFile(path.join(runtime,'wrangler.jsonc'),'utf8'));
if(config.name!=='crm-mail-m1b-local-only'||config.d1_databases[0].remote!==false||config.d1_databases[0].database_id!=='00000000-0000-4000-8000-0000000001b0'||config.services||config.ai||config.send_email||config.vars.MAIL_OUTBOUND_TRANSPORT_MODE!=='disabled')throw Error('Isolation guard');
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE);
await mkdir(evidence,{recursive:true,mode:0o700});
const result={checks:[],cases:[],errors:[],warnings:[],requests:[],external:[],canary:[]};
let canaryAllowed=false;
const check=(ok,label)=>{result.checks.push({label,pass:!!ok});if(!ok)throw Error(label);};
const save=()=>writeFile(path.join(evidence,'browser.json'),JSON.stringify(result,null,2),{mode:0o600});
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE});
const ctx=await browser.newContext({viewport:{width:390,height:844}}),page=await ctx.newPage();page.setDefaultTimeout(20000);
const safe=s=>String(s).replace(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g,'[email]').replace(/\?[^\s)]+/g,'?[redacted]').slice(0,1000);
page.on('pageerror',e=>result.errors.push(safe(e.message)));page.on('console',m=>{if(['error','warning'].includes(m.type()))result.warnings.push(safe(m.text()));});
page.on('response',r=>{let u=new URL(r.url());if(u.pathname.startsWith('/api/mail'))result.requests.push({path:u.pathname,status:r.status(),time:Date.now()});});
await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin==='http://127.0.0.1:3399'&&canaryAllowed){result.canary.push({path:u.pathname,referer:routeSafeReferrer(r.request())});return r.continue();}if(['http:','https:'].includes(u.protocol)&&u.origin!=='http://127.0.0.1:3330'){result.external.push({origin:u.origin,path:u.pathname});return r.abort();}return r.continue();});
function routeSafeReferrer(request){return request.headers()['referer'] ? 'PRESENT' : null;}
const scroller=()=>page.locator('.mail-message-scroll:visible');
async function open(name){const back=page.getByRole('button',{name:/^Back to (Mail|message list)$/});if(await back.isVisible())await back.click();await page.locator('button:visible').filter({hasText:name}).click();await scroller().locator('iframe').waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('.mail-message-scroll')].some(s=>s.clientHeight>0&&s.querySelector('iframe')?.clientHeight>0));await page.waitForTimeout(300);}
async function geometry(marker){return scroller().evaluate((s,marker)=>{const f=s.querySelector('iframe'),d=f.contentDocument,h=f.parentElement.parentElement;const r=e=>{const b=e.getBoundingClientRect();return {left:b.left,top:b.top,bottom:b.bottom,width:b.width,height:b.height};};const fr=r(f),sr=r(s),scale=fr.width/f.clientWidth;const m=[...d.querySelectorAll('p,div,td')].find(e=>e.textContent?.trim()===marker),mr=m&&r(m);const footer=[...document.querySelectorAll('.mail-reading-footer')].find(e=>e.getBoundingClientRect().height);const visible=selector=>{const e=d.querySelector(selector);return e&&d.defaultView.getComputedStyle(e).display!=='none';};return {viewport:[innerWidth,innerHeight],docWidth:document.documentElement.scrollWidth,scroller:{...sr,clientHeight:s.clientHeight,scrollHeight:s.scrollHeight,scrollTop:s.scrollTop},frame:{...fr,naturalWidth:f.clientWidth,naturalHeight:f.clientHeight,innerScrollHeight:d.documentElement.scrollHeight,scale},host:{width:h.clientWidth,scrollWidth:h.scrollWidth,scrollLeft:h.scrollLeft,verticalRange:h.scrollHeight-h.clientHeight},marker:mr?{top:fr.top+mr.top*scale,bottom:fr.top+mr.bottom*scale}:null,markerVisible:!!mr&&fr.top+mr.top*scale>=sr.top-1&&fr.top+mr.bottom*scale<=sr.bottom+1,mobileVisible:visible('.mobile'),desktopVisible:visible('.desktop'),padding:d.querySelector('.layout td')?d.defaultView.getComputedStyle(d.querySelector('.layout td')).padding:null,active:d.querySelectorAll('script,iframe,object,embed,svg,form,input,[onerror],[onclick]').length,executed:!!d.body.dataset.executed,sandbox:f.getAttribute('sandbox'),footerUncovered:[...footer.querySelectorAll('button')].every(e=>{let b=e.getBoundingClientRect();return e.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2));})};},marker);}
async function bottom(marker){let g=await geometry(marker);await page.mouse.move(g.scroller.left+g.scroller.width/2,Math.min(g.scroller.bottom-30,g.scroller.top+150));for(let i=0;i<Math.ceil(g.scroller.scrollHeight/20000)+1;i++){await page.mouse.wheel(0,20000);await page.waitForTimeout(50);}await page.waitForTimeout(150);return geometry(marker);}
try{
 await page.goto('http://127.0.0.1:3330/mail',{waitUntil:'domcontentloaded',timeout:120000});const c=JSON.parse(await readFile(path.join(runtime,'local-login.json'),'utf8'));await page.locator('input[type=email]').fill(c.email);await page.locator('input[type=password]').fill(c.password);const login=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/login'&&r.request().method()==='POST',{timeout:60000});await page.locator('button[type=submit]').click();check((await login).status()===200,'normal synthetic login');await page.waitForURL(u=>!u.pathname.startsWith('/login'));await page.goto('http://127.0.0.1:3330/mail',{waitUntil:'domcontentloaded'});
 for(const size of [[390,844],[390,600],[1280,900]]){
  await page.setViewportSize({width:size[0],height:size[1]});await open('M1B M1H_FIXED_LONG');let top=await geometry('END_M1H_FIXED');check(top.frame.scale===(size[0]===390?top.host.width/top.frame.naturalWidth:1),'default scale '+size);check(top.docWidth===size[0]&&top.host.scrollWidth<=top.host.width+1,'default bounded width '+size);check(top.frame.innerScrollHeight<=top.frame.naturalHeight+1,'no iframe vertical scroll '+size);let end=await bottom('END_M1H_FIXED');check(end.markerVisible&&end.footerUncovered,'fitted final marker/footer '+size);
  if(size[0]===390){await page.mouse.wheel(0,-100000);await page.getByRole('button',{name:'Original width',exact:true}).click();await page.waitForTimeout(150);let original=await geometry('END_M1H_FIXED');result.cases.push({name:'original-observation',size,top,original});check(original.frame.scale===1&&original.host.scrollWidth===top.frame.naturalWidth&&original.docWidth===390,'original natural width contained '+size);await page.mouse.move(original.scroller.left+original.scroller.width/2,Math.min(original.scroller.bottom-30,original.frame.top+60));await page.mouse.wheel(300,0);await page.waitForTimeout(150);check((await geometry('END_M1H_FIXED')).host.scrollLeft>0,'ordinary horizontal pan '+size);await page.mouse.wheel(-1000,0);await page.waitForTimeout(150);end=await bottom('END_M1H_FIXED');check(end.markerVisible&&end.footerUncovered,'original final marker/footer '+size);await page.mouse.wheel(0,-100000);await page.getByRole('button',{name:'Fit to screen',exact:true}).click();await page.waitForTimeout(150);check((await geometry('END_M1H_FIXED')).frame.scale<1,'return to fitted '+size);}
  result.cases.push({name:'fixed-long',size,top,end});await save();
  await open('M1B M1H_RESPONSIVE');let responsive=await geometry('END_M1H_RESPONSIVE');check(responsive.mobileVisible===(size[0]===390)&&responsive.desktopVisible===(size[0]!==390),'responsive visibility '+size);check(responsive.padding===(size[0]===390?'12px':'24px'),'responsive safe table style '+size);if(size[0]===390){await page.getByRole('button',{name:'Original width',exact:true}).click();await page.waitForTimeout(150);let natural=await geometry('END_M1H_RESPONSIVE');check(natural.mobileVisible&&!natural.desktopVisible&&natural.frame.scale===1,'original mode retains mobile media rules '+size);await page.getByRole('button',{name:'Fit to screen',exact:true}).click();await page.waitForTimeout(150);}result.cases.push({name:'responsive',size,responsive});await page.screenshot({path:path.join(evidence,'responsive-'+size.join('x')+'.png')});await save();
 }
 await page.setViewportSize({width:390,height:844});await open('M1B M1H_FLEXIBLE');let flexible=await geometry('END_M1H_FLEX');check(flexible.frame.scale===1&&await page.getByRole('button',{name:'Original width',exact:true}).count()===0,'flexible mail no meaningless control');
 await open('M1B SAFE_WIDE_CONTENT');let extreme=await geometry('ACTUAL_END_WIDE');check(extreme.frame.scale<0.1&&extreme.host.scrollWidth<=extreme.host.width+1,'extreme pre fitted overview');await page.getByRole('button',{name:'Original width',exact:true}).click();await page.waitForTimeout(200);check((await geometry('ACTUAL_END_WIDE')).host.scrollWidth>10000,'extreme original accessible');await open('M1B M1H_FIXED_LONG');check((await geometry('END_M1H_FIXED')).frame.scale<1,'new selection resets mode');
 await page.mouse.move(180,400);await page.mouse.wheel(0,800);await page.waitForTimeout(150);await scroller().evaluate(s=>{window.__m1h={s,f:s.querySelector('iframe'),d:s.querySelector('iframe').contentDocument,scroll:s.scrollTop};});let requestStart=result.requests.length;await page.waitForTimeout(65000);check(await scroller().evaluate(s=>s===window.__m1h.s&&s.querySelector('iframe')===window.__m1h.f&&s.querySelector('iframe').contentDocument===window.__m1h.d&&s.scrollTop===window.__m1h.scroll),'real polling retains document and scroll');result.cases.push({name:'polling',requests:result.requests.slice(requestStart)});
 await open('M1B LONG_HTML');let longEnd=await bottom('ACTUAL_END_LONG');check(longEnd.markerVisible&&longEnd.footerUncovered&&longEnd.frame.naturalHeight>400000&&longEnd.frame.scale===1,'10k paragraph reader remains complete');result.cases.push({name:'10k-long',longEnd});await open('M1B M1H_HOSTILE');let hostile=await geometry('END_M1H_HOSTILE');check(hostile.active===0&&!hostile.executed&&hostile.sandbox==='allow-same-origin','hostile active content blocked');check(result.external.length===0,'zero automatic external resource attempts');result.cases.push({name:'hostile',hostile});await open('M1B M1H_IMAGE_WIDE');check(result.canary.length===0&&result.external.length===0,'wide remote image inert before opt-in');
 canaryAllowed=true;await page.getByRole('button',{name:'Load remote images',exact:true}).click();await page.waitForFunction(()=>{const s=[...document.querySelectorAll('.mail-message-scroll')].find(e=>e.clientHeight>0),i=s?.querySelector('iframe')?.contentDocument?.querySelector('img');return i?.complete&&i.naturalWidth>0;});
 await scroller().evaluate(s=>{window.__imageRef={f:s.querySelector('iframe'),d:s.querySelector('iframe').contentDocument};});const loadedRequests=result.canary.length;check(loadedRequests===1&&result.canary[0].path==='/banner.png'&&result.canary[0].referer===null,'explicit allowlisted load without referrer');
 await page.getByRole('button',{name:'Original width',exact:true}).click();await page.waitForTimeout(250);await page.getByRole('button',{name:'Fit to screen',exact:true}).click();await page.waitForTimeout(250);check(result.canary.length===loadedRequests&&await scroller().evaluate(s=>s.querySelector('iframe')===window.__imageRef.f&&s.querySelector('iframe').contentDocument===window.__imageRef.d),'mode toggles retain document/images without refetch');let imageEnd=await bottom('END_M1H_IMAGE');check(imageEnd.markerVisible&&imageEnd.footerUncovered,'late image height and final marker');canaryAllowed=false;
 for(const [name,count] of [['M1EC CID_SINGLE',1],['M1EC CID_MULTIPLE',3],['M1EC CID_MISSING',0],['M1EC CID_DUPLICATE',0]]){await open(name);await page.waitForFunction(count=>{let d=[...document.querySelectorAll('.mail-message-scroll')].find(e=>e.clientHeight>0)?.querySelector('iframe')?.contentDocument;return d&&(count?[...d.querySelectorAll('img')].filter(i=>i.complete&&i.naturalWidth>0).length===count:d.body.textContent.includes('Inline image unavailable'));},count);check(true,name+' authorized rendering/fail-closed');}
 for(const [name,mode] of [['M1B M1H_RESPONSIVE','Reply'],['M1B ENTERPRISE_TABLE','Reply all'],['M1B REMOTE_IMAGE_ONLY','Forward']]){await open(name);if(mode==='Reply all')await page.getByRole('button',{name:'Actions',exact:true}).click();await page.getByRole('button',{name:mode,exact:true}).click();await page.getByRole('button',{name:'Show quoted content',exact:true}).waitFor();check((await page.locator('[contenteditable=true]').innerText()).trim()==='','separate clean prefix '+mode);await page.getByRole('button',{name:'Show quoted content',exact:true}).click();await page.locator('.mail-compose-quoted iframe').waitFor();await page.waitForTimeout(350);const quote=await page.locator('.mail-compose-quoted iframe').evaluate(f=>({text:f.contentDocument.body.textContent,active:f.contentDocument.querySelectorAll('script,iframe,form,[onclick],[onerror]').length,editable:!!document.querySelector('.mail-compose-quoted [contenteditable=true]'),sandbox:f.getAttribute('sandbox'),recipients:[...document.querySelectorAll('button[aria-label="Remove recipient"]')].map(e=>e.parentElement.textContent),subject:[...document.querySelectorAll('input')].map(i=>i.value).find(v=>/^(Re:|Fwd:)/.test(v))}));check(!quote.editable&&quote.active===0&&quote.sandbox==='allow-same-origin','safe read-only quote '+mode);check(!quote.text.includes('invisible@example.invalid')&&!quote.recipients.some(r=>r.includes('reader@example.invalid')),'Bcc/self excluded '+mode);check(mode==='Forward'?quote.text.includes('Forwarded message')&&quote.subject.startsWith('Fwd:'):quote.text.includes('wrote:')&&quote.subject.startsWith('Re:'),'metadata/subject '+mode);result.cases.push({name:'compose '+mode,subject:quote.subject,recipientCount:quote.recipients.length});await page.getByRole('button',{name:'Back to Mail',exact:true}).click();await page.locator('[contenteditable=true]').waitFor({state:'hidden'});}
 check(result.external.length===0&&result.canary.length===1,'no unintended remote load through reader or quote');result.completed=true;
}catch(e){result.failure=safe(e.message);process.exitCode=1;}finally{await save();console.log(JSON.stringify({completed:result.completed,checks:result.checks.length,failures:result.checks.filter(c=>!c.pass),error:result.failure,external:result.external,errors:result.errors}));await ctx.close();await browser.close();}
