-- Phase 1: Customer source menu tags — final 14 top-level menu (no customers.source changes)
UPDATE customer_tags SET label = '淘宝', updated_at = datetime('now') WHERE tag_key = 'xianyu_taobao';
UPDATE customer_tags SET label = '客户转介绍', updated_at = datetime('now') WHERE tag_key = 'referral';
UPDATE customer_tags SET label = '代理渠道', updated_at = datetime('now') WHERE tag_key = 'agent_client';
UPDATE customer_tags SET label = '其他媒体平台（历史未细分）', is_active = 0, updated_at = datetime('now') WHERE tag_key = 'online_media';

INSERT OR IGNORE INTO customer_tags (id, tag_key, label, is_system, is_active, sort_order, created_at, updated_at) VALUES
  ('ctag-google', 'google', 'Google', 0, 1, 100, datetime('now'), datetime('now')),
  ('ctag-youtube', 'youtube', 'YouTube', 0, 1, 101, datetime('now'), datetime('now')),
  ('ctag-instagram', 'instagram', 'Instagram', 0, 1, 102, datetime('now'), datetime('now')),
  ('ctag-facebook', 'facebook', 'Facebook', 0, 1, 103, datetime('now'), datetime('now')),
  ('ctag-linkedin', 'linkedin', 'LinkedIn（领英）', 0, 1, 104, datetime('now'), datetime('now')),
  ('ctag-tiktok', 'tiktok', 'TikTok', 0, 1, 105, datetime('now'), datetime('now')),
  ('ctag-whatsapp_business', 'whatsapp_business', 'WhatsApp Business', 0, 1, 106, datetime('now'), datetime('now')),
  ('ctag-x_twitter', 'x_twitter', 'X（Twitter）', 0, 1, 107, datetime('now'), datetime('now')),
  ('ctag-threads', 'threads', 'Threads', 0, 1, 108, datetime('now'), datetime('now')),
  ('ctag-telegram', 'telegram', 'Telegram', 0, 1, 109, datetime('now'), datetime('now')),
  ('ctag-snapchat', 'snapchat', 'Snapchat', 0, 1, 110, datetime('now'), datetime('now')),
  ('ctag-dailymotion', 'dailymotion', 'Dailymotion', 0, 1, 111, datetime('now'), datetime('now')),
  ('ctag-tumblr', 'tumblr', 'Tumblr', 0, 1, 112, datetime('now'), datetime('now')),
  ('ctag-wechat_video_channel', 'wechat_video_channel', '视频号', 0, 1, 113, datetime('now'), datetime('now')),
  ('ctag-wechat_official_account', 'wechat_official_account', '公众号', 0, 1, 114, datetime('now'), datetime('now')),
  ('ctag-wechat_search', 'wechat_search', '微信搜一搜', 0, 1, 115, datetime('now'), datetime('now')),
  ('ctag-wechat_moments', 'wechat_moments', '微信朋友圈', 0, 1, 116, datetime('now'), datetime('now')),
  ('ctag-wecom', 'wecom', '企业微信', 0, 1, 117, datetime('now'), datetime('now')),
  ('ctag-wechat_group', 'wechat_group', '微信群', 0, 1, 118, datetime('now'), datetime('now')),
  ('ctag-wechat_miniprogram', 'wechat_miniprogram', '微信小程序', 0, 1, 119, datetime('now'), datetime('now')),
  ('ctag-wechat_other', 'wechat_other', '其他微信渠道', 0, 1, 120, datetime('now'), datetime('now')),
  ('ctag-kuaishou', 'kuaishou', '快手', 0, 1, 121, datetime('now'), datetime('now')),
  ('ctag-xianyu', 'xianyu', '闲鱼', 0, 1, 122, datetime('now'), datetime('now')),
  ('ctag-pinduoduo', 'pinduoduo', '拼多多', 0, 1, 123, datetime('now'), datetime('now')),
  ('ctag-zhihu', 'zhihu', '知乎', 0, 1, 124, datetime('now'), datetime('now')),
  ('ctag-bilibili', 'bilibili', '哔哩哔哩（B站）', 0, 1, 125, datetime('now'), datetime('now')),
  ('ctag-toutiao', 'toutiao', '今日头条', 0, 1, 126, datetime('now'), datetime('now')),
  ('ctag-xigua_video', 'xigua_video', '西瓜视频', 0, 1, 127, datetime('now'), datetime('now')),
  ('ctag-baijiahao', 'baijiahao', '百家号', 0, 1, 128, datetime('now'), datetime('now')),
  ('ctag-baidu_zhidao', 'baidu_zhidao', '百度知道', 0, 1, 129, datetime('now'), datetime('now')),
  ('ctag-baidu_jingyan', 'baidu_jingyan', '百度经验', 0, 1, 130, datetime('now'), datetime('now')),
  ('ctag-baidu_tieba', 'baidu_tieba', '百度贴吧', 0, 1, 131, datetime('now'), datetime('now')),
  ('ctag-qq', 'qq', 'QQ', 0, 1, 132, datetime('now'), datetime('now')),
  ('ctag-ifeng', 'ifeng', '凤凰网', 0, 1, 133, datetime('now'), datetime('now')),
  ('ctag-yidian', 'yidian', '一点资讯', 0, 1, 134, datetime('now'), datetime('now')),
  ('ctag-uc_toutiao', 'uc_toutiao', 'UC头条', 0, 1, 135, datetime('now'), datetime('now')),
  ('ctag-douban', 'douban', '豆瓣', 0, 1, 136, datetime('now'), datetime('now')),
  ('ctag-jianshu', 'jianshu', '简书', 0, 1, 137, datetime('now'), datetime('now')),
  ('ctag-csdn', 'csdn', 'CSDN', 0, 1, 138, datetime('now'), datetime('now')),
  ('ctag-cnblogs', 'cnblogs', '博客园', 0, 1, 139, datetime('now'), datetime('now')),
  ('ctag-segmentfault', 'segmentfault', 'SegmentFault', 0, 1, 140, datetime('now'), datetime('now')),
  ('ctag-oschina', 'oschina', '开源中国（OSChina）', 0, 1, 141, datetime('now'), datetime('now')),
  ('ctag-zsxq', 'zsxq', '知识星球', 0, 1, 142, datetime('now'), datetime('now')),
  ('ctag-dedao', 'dedao', '得到', 0, 1, 143, datetime('now'), datetime('now')),
  ('ctag-kuaikandian', 'kuaikandian', '快看点', 0, 1, 144, datetime('now'), datetime('now')),
  ('ctag-lishipin', 'lishipin', '梨视频', 0, 1, 145, datetime('now'), datetime('now')),
  ('ctag-qutoutiao', 'qutoutiao', '趣头条', 0, 1, 146, datetime('now'), datetime('now')),
  ('ctag-dongfang_toutiao', 'dongfang_toutiao', '东方头条', 0, 1, 147, datetime('now'), datetime('now')),
  ('ctag-xueqiu', 'xueqiu', '雪球', 0, 1, 148, datetime('now'), datetime('now')),
  ('ctag-eastmoney', 'eastmoney', '东方财富', 0, 1, 149, datetime('now'), datetime('now')),
  ('ctag-tonghuashun', 'tonghuashun', '同花顺', 0, 1, 150, datetime('now'), datetime('now')),
  ('ctag-sina_finance', 'sina_finance', '新浪财经', 0, 1, 151, datetime('now'), datetime('now')),
  ('ctag-other_media_platform', 'other_media_platform', '其他媒体平台', 0, 1, 152, datetime('now'), datetime('now')),
  ('ctag-company_website', 'company_website', '公司官网', 0, 1, 153, datetime('now'), datetime('now')),
  ('ctag-partner', 'partner', '合作伙伴', 0, 1, 154, datetime('now'), datetime('now')),
  ('ctag-cross_industry', 'cross_industry', '异业合作', 0, 1, 155, datetime('now'), datetime('now')),
  ('ctag-industry_association', 'industry_association', '行业协会', 0, 1, 156, datetime('now'), datetime('now')),
  ('ctag-chamber_of_commerce', 'chamber_of_commerce', '商会', 0, 1, 157, datetime('now'), datetime('now')),
  ('ctag-cooperation_other', 'cooperation_other', '其他合作渠道', 0, 1, 158, datetime('now'), datetime('now')),
  ('ctag-maimai', 'maimai', '脉脉', 0, 1, 159, datetime('now'), datetime('now')),
  ('ctag-hc360', 'hc360', '慧聪网', 0, 1, 160, datetime('now'), datetime('now')),
  ('ctag-global_sources', 'global_sources', '环球资源（Global Sources）', 0, 1, 161, datetime('now'), datetime('now')),
  ('ctag-dhgate', 'dhgate', '敦煌网（DHgate）', 0, 1, 162, datetime('now'), datetime('now')),
  ('ctag-b2b_other', 'b2b_other', '其他B2B平台', 0, 1, 163, datetime('now'), datetime('now')),
  ('ctag-cold_call', 'cold_call', '陌生电话', 0, 1, 164, datetime('now'), datetime('now')),
  ('ctag-public_company_info', 'public_company_info', '公开企业信息渠道', 0, 1, 165, datetime('now'), datetime('now')),
  ('ctag-outbound_other', 'outbound_other', '其他主动开发', 0, 1, 166, datetime('now'), datetime('now')),
  ('ctag-offline_event', 'offline_event', '线下活动', 0, 1, 167, datetime('now'), datetime('now')),
  ('ctag-offline_salon', 'offline_salon', '线下沙龙', 0, 1, 168, datetime('now'), datetime('now')),
  ('ctag-industry_expo', 'industry_expo', '行业展会', 0, 1, 169, datetime('now'), datetime('now')),
  ('ctag-company_lecture', 'company_lecture', '企业讲座', 0, 1, 170, datetime('now'), datetime('now')),
  ('ctag-public_class', 'public_class', '公开课', 0, 1, 171, datetime('now'), datetime('now')),
  ('ctag-webinar', 'webinar', '网络研讨会（Webinar）', 0, 1, 172, datetime('now'), datetime('now')),
  ('ctag-community_event', 'community_event', '社群活动', 0, 1, 173, datetime('now'), datetime('now')),
  ('ctag-walk_in', 'walk_in', '自然到访', 0, 1, 174, datetime('now'), datetime('now')),
  ('ctag-offline_other', 'offline_other', '其他线下渠道', 0, 1, 175, datetime('now'), datetime('now')),
  ('ctag-inbound_inquiry', 'inbound_inquiry', '主动咨询', 0, 1, 176, datetime('now'), datetime('now')),
  ('ctag-other_online', 'other_online', '其他线上渠道', 0, 1, 177, datetime('now'), datetime('now')),
  ('ctag-other_offline', 'other_offline', '其他线下渠道', 0, 1, 178, datetime('now'), datetime('now')),
  ('ctag-source_unknown', 'source_unknown', '来源不明', 0, 1, 179, datetime('now'), datetime('now'));
