export type AdminUserView = {
  id: string;
  name: string;
  email: string;
  role: string;
  status: "active" | "disabled" | "deleted";
  failed_login_count: number;
  locked_until: string | null;
  is_locked: boolean;
  lockout_exempt: boolean;
  last_failed_login_at: string | null;
  locked_at: string | null;
  lock_reason: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  deleted_by_name: string | null;
  transferred_customer_count: number | null;
  transferred_to_admin_name: string | null;
  primary_assignees_transferred_count: number | null;
  collaborator_assignees_removed_count: number | null;
  last_login_at: string | null;
  recent_login_count: number;
  cloudflare_access_email: string | null;
  first_login_at?: string | null;
  pool_claim_paused?: boolean;
  pool_claim_quota_override?: number | null;
  pool_claim_cooldown_hours_override?: number | null;
  pool_claim_effective_quota?: number;
  pool_claim_effective_cooldown_hours?: number;
  pool_claim_eligibility_at?: string | null;
  pool_claim_remaining_days?: number;
  pool_claim_eligibility_status?: "paused" | "protected" | "eligible";
  device_approved_count: number;
  device_pending_count: number;
};

export type LoginLogView = {
  id: string;
  email: string;
  success: boolean;
  failure_reason: string | null;
  ip_address: string | null;
  user_agent: string | null;
  created_at: string;
};
