import type { KnowledgeRole } from "../../../drizzle/schema/knowledge-user-roles";

export const KNOWLEDGE_POLICY_ID = "singleton" as const;
export const KNOWLEDGE_MAX_FAILED_ATTEMPTS = 5;
export const KNOWLEDGE_LOCK_DURATION_MS = 15 * 60 * 1000;

export const KNOWLEDGE_ROLES = [
  "viewer",
  "contributor",
  "reviewer",
  "knowledge_admin",
] as const satisfies readonly KnowledgeRole[];

export const KNOWLEDGE_ROLE_RANK: Record<KnowledgeRole, number> = {
  viewer: 1,
  contributor: 2,
  reviewer: 3,
  knowledge_admin: 4,
};

export const KNOWLEDGE_ROLE_LABELS: Record<KnowledgeRole, string> = {
  viewer: "Viewer",
  contributor: "Contributor",
  reviewer: "Reviewer",
  knowledge_admin: "Knowledge Admin",
};

export const KNOWLEDGE_ERROR_CODES = {
  NOT_INITIALIZED: "KNOWLEDGE_NOT_INITIALIZED",
  ALREADY_INITIALIZED: "KNOWLEDGE_ALREADY_INITIALIZED",
  ACCESS_REQUIRED: "KNOWLEDGE_ACCESS_REQUIRED",
  ROLE_REQUIRED: "KNOWLEDGE_ROLE_REQUIRED",
  ADMIN_REQUIRED: "KNOWLEDGE_ADMIN_REQUIRED",
  PASSWORD_INVALID: "KNOWLEDGE_PASSWORD_INVALID",
  PASSWORD_LOCKED: "KNOWLEDGE_PASSWORD_LOCKED",
  PASSWORD_NOT_CONFIGURED: "KNOWLEDGE_PASSWORD_NOT_CONFIGURED",
  LAST_ADMIN: "KNOWLEDGE_LAST_ADMIN",
  ROLE_INVALID: "KNOWLEDGE_ROLE_INVALID",
  CATEGORY_INVALID: "KNOWLEDGE_CATEGORY_INVALID",
  CATEGORY_NOT_FOUND: "KNOWLEDGE_CATEGORY_NOT_FOUND",
  CATEGORY_HAS_ARTICLES: "KNOWLEDGE_CATEGORY_HAS_ARTICLES",
  CATEGORY_DELETE_DISABLED: "KNOWLEDGE_CATEGORY_DELETE_DISABLED",
  ARTICLE_INVALID: "KNOWLEDGE_ARTICLE_INVALID",
  ARTICLE_NOT_FOUND: "KNOWLEDGE_ARTICLE_NOT_FOUND",
  ARTICLE_ACCESS_DENIED: "KNOWLEDGE_ARTICLE_ACCESS_DENIED",
  ARTICLE_CONFLICT: "KNOWLEDGE_ARTICLE_CONFLICT",
  ARTICLE_NOT_EDITABLE: "KNOWLEDGE_ARTICLE_NOT_EDITABLE",
  SOURCE_INVALID: "KNOWLEDGE_SOURCE_INVALID",
  SOURCE_NOT_FOUND: "KNOWLEDGE_SOURCE_NOT_FOUND",
  SOURCE_ACCESS_DENIED: "KNOWLEDGE_SOURCE_ACCESS_DENIED",
  SOURCE_ALREADY_CONVERTED: "SOURCE_ALREADY_CONVERTED",
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  MIME_MISMATCH: "MIME_MISMATCH",
  UNSAFE_FILENAME: "UNSAFE_FILENAME",
  TEXT_EXTRACTION_FAILED: "TEXT_EXTRACTION_FAILED",
  TEXT_EXTRACTION_UNAVAILABLE: "TEXT_EXTRACTION_UNAVAILABLE",
  AI_ORGANIZATION_FAILED: "AI_ORGANIZATION_FAILED",
  AI_OUTPUT_INVALID: "AI_OUTPUT_INVALID",
  AI_RUN_CONFLICT: "AI_RUN_CONFLICT",
  STORAGE_UNAVAILABLE: "KNOWLEDGE_STORAGE_UNAVAILABLE",
  REVIEW_INVALID: "KNOWLEDGE_REVIEW_INVALID",
  REVIEW_NOT_FOUND: "KNOWLEDGE_REVIEW_NOT_FOUND",
  REVIEW_ACCESS_DENIED: "KNOWLEDGE_REVIEW_ACCESS_DENIED",
  REVIEW_CONFLICT: "KNOWLEDGE_REVIEW_CONFLICT",
  REVIEW_NOTE_REQUIRED: "KNOWLEDGE_REVIEW_NOTE_REQUIRED",
  REVIEW_SELF_APPROVAL: "KNOWLEDGE_REVIEW_SELF_APPROVAL",
  REVIEW_ARCHIVED: "KNOWLEDGE_REVIEW_ARCHIVED",
  REVIEW_ASSIGNMENT_INVALID: "KNOWLEDGE_REVIEW_ASSIGNMENT_INVALID",
  SEARCH_INVALID: "KNOWLEDGE_SEARCH_INVALID",
  AI_RATE_LIMITED: "KNOWLEDGE_AI_RATE_LIMITED",
  AI_BUSY: "KNOWLEDGE_AI_BUSY",
  AI_TIMEOUT: "KNOWLEDGE_AI_TIMEOUT",
  AI_PROVIDER_FAILED: "KNOWLEDGE_AI_PROVIDER_FAILED",
  AI_QA_OUTPUT_INVALID: "KNOWLEDGE_AI_OUTPUT_INVALID",
  AI_NO_SOURCES: "KNOWLEDGE_AI_NO_SOURCES",
  AI_CITATION_INVALID: "KNOWLEDGE_AI_CITATION_INVALID",
} as const;

export type KnowledgeCapability =
  | "enter"
  | "submit"
  | "review"
  | "manage";

export const KNOWLEDGE_VISIBILITY = [
  "team",
  "restricted",
  "owner",
] as const;

export type KnowledgeVisibility = (typeof KNOWLEDGE_VISIBILITY)[number];
