import type { MailMailbox, MailMessage } from "./types";

export const MOCK_ADMIN_MAILBOX: MailMailbox = {
  address: "daniel@echfronthk.com",
  label: "personal",
  displayName: "Daniel",
  autoReplyEnabled: false,
};

export const MOCK_STAFF_A_MAILBOX: MailMailbox = {
  address: "a@echfronthk.com",
  label: "personal",
  displayName: "Employee A",
  autoReplyEnabled: false,
};

export const MOCK_STAFF_B_MAILBOX: MailMailbox = {
  address: "b@echfronthk.com",
  label: "personal",
  displayName: "Employee B",
  autoReplyEnabled: false,
};

export const MOCK_SHARED_MAILBOX: MailMailbox = {
  address: "hello@echfronthk.com",
  label: "shared",
  displayName: "ECHFRONT Hello",
  autoReplyEnabled: true,
};

/** Mock authorized sender identity for admin compose (prototype only). */
export const MOCK_CLIENT_SERVICE_SENDER: MailMailbox = {
  address: "hello@echfronthk.com",
  label: "shared",
  displayName: "ECHFRONT Client Service",
  autoReplyEnabled: true,
};

export const MOCK_SIGNATURE_HTML = `<p><strong>Daniel</strong><br/>ECHFRONT | 領峯環球<br/><a href="mailto:daniel@echfronthk.com">daniel@echfronthk.com</a></p>`;

export const MOCK_STAFF_SIGNATURE_HTML = `<p><strong>Employee A</strong><br/>ECHFRONT | 領峯環球<br/><a href="mailto:a@echfronthk.com">a@echfronthk.com</a></p>`;

export function createInitialMockMessages(): MailMessage[] {
  return [
    {
      id: "msg-1",
      folder: "inbox",
      mailbox: "a@echfronthk.com",
      fromName: "John Smith",
      fromEmail: "john@gmail.com",
      to: ["a@echfronthk.com"],
      cc: ["mary@example.com"],
      subject: "Re: Bank Account",
      preview: "Please find attached the documents you requested…",
      body: "Hello Daniel,\n\nPlease find attached the documents you requested for the bank account opening.\n\nBest regards,\nJohn",
      sentAt: "2026-08-18T10:32:00+08:00",
      isUnread: true,
      hasAttachment: true,
      attachments: [
        { id: "att-1", name: "Passport.pdf", sizeLabel: "1.8 MB", kind: "attachment" },
      ],
      customerMatch: { id: "cust-1", name: "John Smith" },
      assignment: "none",
      isImportant: true,
      sensitivity: "sensitive",
    },
    {
      id: "msg-2",
      folder: "inbox",
      mailbox: "a@echfronthk.com",
      fromName: "Sarah Chen",
      fromEmail: "sarah.chen@external.io",
      to: ["a@echfronthk.com"],
      subject: "Partnership inquiry",
      preview: "We would like to discuss a potential collaboration…",
      body: "Hi,\n\nWe would like to discuss a potential collaboration with ECHFRONT.\n\nSarah",
      sentAt: "2026-08-17T16:45:00+08:00",
      isUnread: false,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "none",
    },
    {
      id: "msg-3",
      folder: "inbox",
      mailbox: "hello@echfronthk.com",
      fromName: "Michael Wong",
      fromEmail: "michael@client.hk",
      to: ["hello@echfronthk.com"],
      subject: "General enquiry",
      preview: "I saw your website and would like more information…",
      body: "Dear ECHFRONT team,\n\nI saw your website and would like more information about your services.\n\nMichael",
      sentAt: "2026-08-18T09:15:00+08:00",
      isUnread: true,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "unassigned",
      processingStatus: "unclaimed",
      assigneeId: null,
      readByUserIds: [],
    },
    {
      id: "msg-4",
      folder: "inbox",
      mailbox: "hello@echfronthk.com",
      fromName: "Lisa Park",
      fromEmail: "lisa@startup.co",
      to: ["hello@echfronthk.com"],
      subject: "Follow up on consultation",
      preview: "Thank you for the call yesterday…",
      body: "Hello,\n\nThank you for the call yesterday. Looking forward to the next steps.\n\nLisa",
      sentAt: "2026-08-17T14:20:00+08:00",
      isUnread: false,
      hasAttachment: true,
      attachments: [
        {
          id: "att-2",
          name: "Bank Documents.zip",
          sizeLabel: "86 MB",
          kind: "secure_file",
        },
      ],
      customerMatch: { id: "cust-2", name: "Lisa Park" },
      assignment: "assigned_to_me",
      assignedToName: "Employee A",
      processingStatus: "in_progress",
      assigneeId: "staff-a",
      readByUserIds: ["staff-a"],
    },
    {
      id: "msg-5",
      folder: "inbox",
      mailbox: "hello@echfronthk.com",
      fromName: "Robert Lee",
      fromEmail: "robert@example.com",
      to: ["hello@echfronthk.com"],
      subject: "Contract review",
      preview: "Please review the attached contract at your earliest…",
      body: "Hi team,\n\nPlease review the attached contract at your earliest convenience.\n\nRobert",
      sentAt: "2026-08-16T11:00:00+08:00",
      isUnread: true,
      hasAttachment: false,
      attachments: [],
      customerMatch: { id: "cust-robert", name: "Robert Lee" },
      assignment: "assigned_to_other",
      assignedToName: "Employee B",
      processingStatus: "in_progress",
      assigneeId: "staff-b",
      readByUserIds: ["staff-b"],
    },
    {
      id: "msg-shared-waiting",
      folder: "inbox",
      mailbox: "hello@echfronthk.com",
      fromName: "Anna Wu",
      fromEmail: "anna@partner.hk",
      to: ["hello@echfronthk.com"],
      subject: "Document follow-up",
      preview: "Following up on the documents we discussed…",
      body: "Hi team,\n\nFollowing up on the documents we discussed last week.\n\nAnna",
      sentAt: "2026-08-18T08:30:00+08:00",
      isUnread: true,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "assigned_to_me",
      assignedToName: "Employee A",
      processingStatus: "waiting_customer",
      assigneeId: "staff-a",
      readByUserIds: [],
    },
    {
      id: "msg-shared-completed",
      folder: "inbox",
      mailbox: "hello@echfronthk.com",
      fromName: "Vendor Co",
      fromEmail: "vendor@supply.hk",
      to: ["hello@echfronthk.com"],
      subject: "Order confirmation",
      preview: "Your order has been processed successfully…",
      body: "Hello,\n\nYour order has been processed successfully.\n\nVendor Co",
      sentAt: "2026-08-15T16:00:00+08:00",
      isUnread: false,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "assigned_to_other",
      assignedToName: "Employee B",
      processingStatus: "completed",
      assigneeId: "staff-b",
      readByUserIds: ["staff-a", "staff-b", "admin"],
    },
    {
      id: "msg-6",
      folder: "pending_approval",
      mailbox: "a@echfronthk.com",
      fromName: "Employee A",
      fromEmail: "a@echfronthk.com",
      to: ["robert@example.com"],
      subject: "Follow-up on account opening",
      preview: "Following up regarding the account opening process…",
      body: "Dear Sir/Madam,\n\nFollowing up regarding the account opening process.\n\nRegards,\nEmployee A",
      sentAt: "2026-08-18T08:00:00+08:00",
      isUnread: false,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "none",
      submittedByName: "Employee A",
      submittedAt: "2026-08-18T08:05:00+08:00",
    },
    {
      id: "msg-7",
      folder: "returned",
      mailbox: "a@echfronthk.com",
      fromName: "Employee A",
      fromEmail: "a@echfronthk.com",
      to: ["prospect@mail.com"],
      subject: "Introduction to ECHFRONT",
      preview: "Thank you for your interest in our services…",
      body: "Thank you for your interest in our services. We would be happy to schedule a call.",
      sentAt: "2026-08-15T10:00:00+08:00",
      isUnread: true,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "none",
      submittedByName: "Employee A",
      submittedAt: "2026-08-15T10:10:00+08:00",
      returnReason: "Please add more detail about the service packages.",
    },
    {
      id: "msg-8",
      folder: "sent",
      mailbox: "daniel@echfronthk.com",
      fromName: "Daniel",
      fromEmail: "daniel@echfronthk.com",
      to: ["partner@vendor.com"],
      subject: "Meeting confirmation",
      preview: "Confirmed — see you Tuesday at 2pm.",
      body: "Hi,\n\nConfirmed — see you Tuesday at 2pm.\n\nDaniel",
      sentAt: "2026-08-14T15:30:00+08:00",
      isUnread: false,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "none",
      deliveryStatus: "delivered",
      deliveryDetail: "Recipient mail server accepted the message.",
    },
    {
      id: "msg-9",
      folder: "pending_my_approval",
      mailbox: "a@echfronthk.com",
      fromName: "Employee A",
      fromEmail: "a@echfronthk.com",
      to: ["john@gmail.com"],
      cc: ["manager@echfronthk.com"],
      subject: "Re: Bank Account — follow up",
      preview: "Following up on the bank account documents…",
      body: "Hi John,\n\nFollowing up on the bank account documents. Please let us know if you need anything else.\n\nEmployee A",
      sentAt: "2026-08-18T07:30:00+08:00",
      isUnread: true,
      hasAttachment: true,
      attachments: [
        { id: "att-3", name: "Checklist.pdf", sizeLabel: "420 KB", kind: "attachment" },
      ],
      customerMatch: { id: "cust-1", name: "John Smith" },
      assignment: "none",
      submittedByName: "Employee A",
      submittedAt: "2026-08-18T07:35:00+08:00",
    },
    {
      id: "msg-10",
      folder: "draft",
      mailbox: "a@echfronthk.com",
      fromName: "Employee A",
      fromEmail: "a@echfronthk.com",
      to: ["draft@example.com"],
      subject: "Draft — onboarding steps",
      preview: "Here are the onboarding steps we discussed…",
      body: "Here are the onboarding steps we discussed during our call.",
      sentAt: "2026-08-18T06:00:00+08:00",
      isUnread: false,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "none",
      draftUpdatedAt: "2026-08-18T06:00:00+08:00",
    },
    {
      id: "msg-11",
      folder: "pending",
      mailbox: "a@echfronthk.com",
      fromName: "Anna Wu",
      fromEmail: "anna@partner.hk",
      to: ["a@echfronthk.com"],
      subject: "Document request",
      preview: "Could you send the latest brochure?",
      body: "Hi,\n\nCould you send the latest brochure?\n\nAnna",
      sentAt: "2026-08-17T09:00:00+08:00",
      isUnread: false,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "none",
    },
    {
      id: "msg-13",
      folder: "pending_my_approval",
      mailbox: "a@echfronthk.com",
      fromName: "Employee A",
      fromEmail: "a@echfronthk.com",
      to: ["robert@example.com"],
      subject: "Follow-up on account opening",
      preview: "Following up regarding the account opening process…",
      body: "Dear Sir/Madam,\n\nFollowing up regarding the account opening process.\n\nRegards,\nEmployee A",
      sentAt: "2026-08-18T08:00:00+08:00",
      isUnread: true,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "none",
      submittedByName: "Employee A",
      submittedAt: "2026-08-18T08:05:00+08:00",
    },
    {
      id: "msg-12",
      folder: "inbox",
      mailbox: "daniel@echfronthk.com",
      fromName: "Finance Team",
      fromEmail: "finance@echfronthk.com",
      to: ["daniel@echfronthk.com"],
      subject: "Monthly report ready",
      preview: "The August finance report is ready for review.",
      body: "Hi Daniel,\n\nThe August finance report is ready for review.\n\nFinance Team",
      sentAt: "2026-08-18T08:45:00+08:00",
      isUnread: true,
      hasAttachment: true,
      attachments: [
        { id: "att-4", name: "August-Report.xlsx", sizeLabel: "2.1 MB", kind: "attachment" },
      ],
      customerMatch: null,
      assignment: "none",
    },
    {
      id: "msg-14",
      folder: "sent",
      mailbox: "a@echfronthk.com",
      fromName: "Employee A",
      fromEmail: "a@echfronthk.com",
      to: ["invalid@bounce.test"],
      subject: "Invoice follow-up",
      preview: "Please find the updated invoice attached…",
      body: "Hi,\n\nPlease find the updated invoice attached.\n\nEmployee A",
      sentAt: "2026-08-17T11:00:00+08:00",
      isUnread: false,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "none",
      deliveryStatus: "bounced",
      deliveryDetail: "Mailbox unavailable (550 5.1.1).",
    },
    {
      id: "msg-15",
      folder: "sent",
      mailbox: "daniel@echfronthk.com",
      fromName: "Daniel",
      fromEmail: "daniel@echfronthk.com",
      to: ["ops@vendor.com"],
      subject: "Service outage notice",
      preview: "We are investigating a temporary delivery delay…",
      body: "Team,\n\nWe are investigating a temporary delivery delay.\n\nDaniel",
      sentAt: "2026-08-18T07:00:00+08:00",
      isUnread: false,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "none",
      deliveryStatus: "deferred",
      deliveryDetail: "Remote server temporarily unavailable.",
    },
    {
      id: "msg-16",
      folder: "sent",
      mailbox: "a@echfronthk.com",
      fromName: "Employee A",
      fromEmail: "a@echfronthk.com",
      to: ["client@external.io"],
      subject: "Contract draft",
      preview: "Sharing the contract draft for review…",
      body: "Hello,\n\nSharing the contract draft for review.\n\nEmployee A",
      sentAt: "2026-08-18T09:30:00+08:00",
      isUnread: false,
      hasAttachment: true,
      attachments: [
        { id: "att-5", name: "Contract-v2.pdf", sizeLabel: "540 KB", kind: "attachment" },
      ],
      customerMatch: null,
      assignment: "none",
      deliveryStatus: "failed",
      deliveryDetail: "SMTP authentication error (prototype).",
      sensitivity: "restricted",
    },
    {
      id: "msg-trash-1",
      folder: "trash",
      mailbox: "daniel@echfronthk.com",
      fromName: "Newsletter",
      fromEmail: "news@marketing.io",
      to: ["daniel@echfronthk.com"],
      subject: "August newsletter",
      preview: "Your monthly digest of industry updates…",
      body: "Your monthly digest of industry updates.",
      sentAt: "2026-08-10T09:00:00+08:00",
      isUnread: false,
      hasAttachment: false,
      attachments: [],
      customerMatch: null,
      assignment: "none",
    },
  ];
}

export const MAIL_PROTOTYPE_UNREAD_BADGE = 6;
