/** Shared layout / color fragments for CRM SaaS UI */
export const ui = {
  page: "mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 lg:py-8",
  textPrimary: "crm-text",
  textSecondary: "crm-text-secondary",
  link: "link-primary",
  sectionTitle: "section-title",
  pageTitle: "page-title",
  pageDescription: "page-description",
  touchTarget: "min-h-11 min-w-11",
  customerName: "crm-customer-name",
  customerCode: "crm-customer-code",
  customerDetail: {
    sectionTitle: "customer-detail-section-title",
    subsectionTitle: "customer-detail-subsection-title",
    label: "customer-detail-label",
    value: "customer-detail-value",
    strongValue: "customer-detail-strong-value",
    codeValue: "customer-detail-code-value",
    muted: "customer-detail-muted",
    row: "customer-detail-row",
    revealBtn: "customer-detail-reveal-btn",
    backLink: "customer-detail-back-link",
    callout: "customer-detail-callout",
    badgeNeutral: "customer-detail-badge-neutral",
    badgeInfo: "customer-detail-badge-info",
  },
} as const;
