import { SEED_IDS } from "@/lib/constants/seed-ids";

/** Deterministic namespace for Phase 2H-5B local attachment download verification. */
export const LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX =
  "LOCAL_MAIL_ATTACHMENT_VERIFY_2H5B";

export const LOCAL_MAIL_ATTACHMENT_VERIFY_OPT_IN_ENV =
  "CRM_ALLOW_LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE" as const;

export const LOCAL_MAIL_ATTACHMENT_VERIFY_R2_KEY_PREFIX =
  "mail/local-verify/2h5b/" as const;

export const LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_ACTORS = {
  admin: SEED_IDS.admin,
  staffA: SEED_IDS.staffA,
  staffB: SEED_IDS.staffB,
} as const;

export const LOCAL_MAIL_ATTACHMENT_VERIFY_MAILBOX_IDS = {
  staffPersonal: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MB-STAFF-A`,
  staffBPrivate: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MB-STAFF-B`,
  shared: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MB-SHARED`,
} as const;

export const LOCAL_MAIL_ATTACHMENT_VERIFY_MESSAGE_IDS = {
  cleanPdf: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-CLEAN-PDF`,
  cleanPng: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-CLEAN-PNG`,
  cleanBinary: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-CLEAN-BIN`,
  unscanned: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-UNSCANNED`,
  blocked: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-BLOCKED`,
  scanFailed: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-SCAN-FAILED`,
  secureFile: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-SECURE-FILE`,
  missingR2: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-MISSING-R2`,
  sharedClean: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-SHARED-CLEAN`,
  unauthorizedMailbox: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-UNAUTHORIZED`,
  headerInjection: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-HEADER-INJ`,
  sharedFileMessageA: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-SHARED-FILE-A`,
  sharedFileMessageB: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-SHARED-FILE-B`,
  trashedClean: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-MSG-TRASHED`,
} as const;

export const LOCAL_MAIL_ATTACHMENT_VERIFY_ATTACHMENT_IDS = {
  cleanPdf: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-CLEAN-PDF`,
  cleanPng: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-CLEAN-PNG`,
  cleanBinary: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-CLEAN-BIN`,
  unscanned: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-UNSCANNED`,
  blocked: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-BLOCKED`,
  scanFailed: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-SCAN-FAILED`,
  secureFile: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-SECURE-FILE`,
  missingR2: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-MISSING-R2`,
  sharedClean: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-SHARED-CLEAN`,
  unauthorizedMailbox: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-UNAUTHORIZED`,
  headerInjection: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-HEADER-INJ`,
  sharedFileA: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-SHARED-FILE-A`,
  sharedFileB: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-SHARED-FILE-B`,
  trashedClean: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-ATT-TRASHED`,
} as const;

export const LOCAL_MAIL_ATTACHMENT_VERIFY_STORED_FILE_IDS = {
  cleanPdf: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-CLEAN-PDF`,
  cleanPng: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-CLEAN-PNG`,
  cleanBinary: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-CLEAN-BIN`,
  unscanned: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-UNSCANNED`,
  blocked: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-BLOCKED`,
  scanFailed: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-SCAN-FAILED`,
  secureFile: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-SECURE-FILE`,
  missingR2: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-MISSING-R2`,
  sharedClean: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-SHARED-CLEAN`,
  unauthorizedMailbox: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-UNAUTHORIZED`,
  headerInjection: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-HEADER-INJ`,
  sharedFile: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-SHARED-REUSE`,
  trashedClean: `${LOCAL_MAIL_ATTACHMENT_VERIFY_FIXTURE_PREFIX}-FILE-TRASHED`,
} as const;

export const LOCAL_MAIL_ATTACHMENT_VERIFY_ADDRESSES = {
  staffPersonalMailbox: "local-mail-attachment-verify-2h5b-staff-a@echfronthk.com",
  staffBPrivateMailbox: "local-mail-attachment-verify-2h5b-staff-b@echfronthk.com",
  sharedMailbox: "local-mail-attachment-verify-2h5b-shared@echfronthk.com",
  inboundSender: "local-mail-attachment-verify-2h5b-sender@echfronthk.test",
  toRecipient: "local-mail-attachment-verify-2h5b-to@echfronthk.test",
} as const;

export const LOCAL_MAIL_ATTACHMENT_VERIFY_TIMESTAMP_BASE =
  "2026-08-23T16:00:00.000Z";

export function attachmentFixtureTimestamp(offsetMinutes: number): string {
  const baseMs = Date.parse(LOCAL_MAIL_ATTACHMENT_VERIFY_TIMESTAMP_BASE);
  return new Date(baseMs - offsetMinutes * 60_000).toISOString();
}

export const LOCAL_MAIL_ATTACHMENT_VERIFY_SUBJECT_PREFIX =
  "[LOCAL ATTACH VERIFY]";

export function attachmentFixtureSubject(label: string): string {
  return `${LOCAL_MAIL_ATTACHMENT_VERIFY_SUBJECT_PREFIX} ${label}`;
}

export const LOCAL_MAIL_ATTACHMENT_VERIFY_HEADER_INJECTION_FILENAME =
  'report"\r\nX-Injected: yes\r\n; filename="safe.pdf';
