export const QUICK_ENTRY_SUBMISSION_STATUS_PROCESSING = "processing" as const;
export const QUICK_ENTRY_SUBMISSION_STATUS_COMPLETED = "completed" as const;

export const QUICK_ENTRY_ROW_STATUS_INVALID = "invalid" as const;
export const QUICK_ENTRY_ROW_STATUS_DUPLICATE = "duplicate" as const;
export const QUICK_ENTRY_ROW_STATUS_CREATED = "created" as const;
export const QUICK_ENTRY_ROW_STATUS_FAILED = "failed" as const;

export const QUICK_ENTRY_SUBMISSION_LEASE_SECONDS = 120;
/** Renew lease when elapsed >= this many seconds during long batch processing. */
export const QUICK_ENTRY_SUBMISSION_LEASE_HEARTBEAT_SECONDS = 60;
export const QUICK_ENTRY_SUBMISSION_RETENTION_DAYS = 30;
export const QUICK_ENTRY_SUBMISSION_CLEANUP_LIMIT = 50;
export const QUICK_ENTRY_BATCH_MAX_ROWS = 20;

export const QUICK_ENTRY_CLIENT_ROW_ID_MAX_LENGTH = 64;
export const QUICK_ENTRY_CLIENT_ROW_ID_RE = /^[A-Za-z0-9_-]+$/;

/** UUID v4: version nibble 4, variant 8/9/a/b. */
export const QUICK_ENTRY_SUBMISSION_ID_UUID_V4_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export const QUICK_ENTRY_SUBMISSION_ERROR_CODES = {
  IDEMPOTENCY_CONFLICT: "QUICK_ENTRY_IDEMPOTENCY_CONFLICT",
  SUBMISSION_PROCESSING: "QUICK_ENTRY_SUBMISSION_PROCESSING",
  SUBMISSION_NOT_FOUND: "QUICK_ENTRY_SUBMISSION_NOT_FOUND",
  SUBMISSION_INCOMPLETE: "QUICK_ENTRY_SUBMISSION_INCOMPLETE",
  SUBMISSION_ALREADY_COMPLETED: "QUICK_ENTRY_SUBMISSION_ALREADY_COMPLETED",
  SUBMISSION_ROW_CONFLICT: "QUICK_ENTRY_SUBMISSION_ROW_CONFLICT",
  SUBMISSION_LEASE_LOST: "QUICK_ENTRY_SUBMISSION_LEASE_LOST",
  SUBMISSION_ID_INVALID: "QUICK_ENTRY_SUBMISSION_ID_INVALID",
  CLIENT_ROW_ID_INVALID: "QUICK_ENTRY_CLIENT_ROW_ID_INVALID",
  CLIENT_ROW_ID_DUPLICATE: "QUICK_ENTRY_CLIENT_ROW_ID_DUPLICATE",
  ROW_PAYLOAD_INVALID: "QUICK_ENTRY_SUBMISSION_ROW_PAYLOAD_INVALID",
  BATCH_EMPTY: "QUICK_ENTRY_BATCH_EMPTY",
  BATCH_TOO_LARGE: "QUICK_ENTRY_BATCH_TOO_LARGE",
  BATCH_INVALID: "QUICK_ENTRY_BATCH_INVALID",
  CUSTOMER_CREATE_FAILED: "QUICK_ENTRY_CUSTOMER_CREATE_FAILED",
} as const;
